
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: mysecretpassword
  host: localhost
  port: 5432

development:
  <<: *default
  database: sns_server

production:
  <<: *default
  database: sns_server